Repository rainbowgon/opentheDoor-frontend, pull requests merged in 2023-11, with the labels that each got.

#27 [fix] App.tsx 누락 부분 수정 및 prettierc quoute double
  .eslintrc.js
  .prettierrc.js
  App.tsx
  components/listItem/ListItem.tsx
Labels: 🚨 fix

#30 [feat] 안드로이드 초기 버전 배포
  .gitignore
  android/app/build.gradle
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/java/com/openthedoor/MainActivity.java
  android/gradle.properties
  components/CheckBox/CustomCheckBox.tsx
  components/ListItem/ListItem.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/LoginScreen/LoginScreen.tsx
Labels: 🚩 distribution

#31 [feat] 회원가입 페이지 구조 제작
  screens/SignUpScreen/SignUpScreen.tsx
Labels: 💡 feature

#34 [fix] gitignore 업데이트
  .gitignore
Labels: 🚨 fix

#35 [feat] 테마 상세 (ThemeDetailScreen) 페이지 구조 제작
  App.tsx
  components/BarGraph/BarGraph.tsx
  components/BarGraph/components/BarGraphItem/BarGraphItem.tsx
  components/InfoCard/InfoCard.tsx
  components/_AdminFabGroup/AdminRightNavigation.tsx
  components/_AdminRightNavigation/AdminRightNavigation.tsx
  components/infoCard/InfoCard.tsx
  index.js
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature

#37 [feat] 메인 페이지 컴포넌트 및 레이아웃
  components/Header/Header.tsx
  components/InfoCard/InfoCard.tsx
  components/Input/Input.tsx
  components/header/Header.tsx
  components/infoCard/InfoCard.tsx
  components/input/Input.tsx
  screens/BookmarkListScreen/BookmarkListScreen.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/HomeScreen/components/BookmarkedTheme/BookmarkedTheme.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitle.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
Labels: 💡 feature

#40 [fix] git 내에 올라가있는 더미 파일 삭제
  components/button/CustomButton.tsx
  components/dropdown/Dropdown.tsx
  components/fab/Fab.tsx
  components/header/Header.tsx
  components/infoCard/InfoCard.tsx
  components/input/Input.tsx
  components/listItem/ListItem.tsx
Labels: 🚨 fix

#42 [feat] 페이지 구조 제작
  screens/MypageScreen/MypageScreen.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/NonUserFeatureList/NonUserFeatureList.tsx
  screens/MypageScreen/components/ReservationInfo/ReservationInfo.tsx
  screens/MypageScreen/components/UserFeatureList/UserFeatureList.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
Labels: 💡 feature

#44 [feat] 페이지 구조 제작(설정, 개인정보 수정, 예약 대기, 북마크 내역)
  components/InfoCard/InfoCard.tsx
  screens/BookmarkListScreen/BookmarkListScreen.tsx
  screens/ProfileUpdateScreen/ProfileUpdateScreen.tsx
  screens/ReservationWaitingScreen/ReservationWaitingScreen.tsx
  screens/SettingScreen/SettingScreen.tsx
Labels: 💡 feature

#46 [feat] 예약 내역 페이지 레이아웃
  components/InfoCard/InfoCard.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
Labels: 💡 feature

#48 [feat] 예약, 알람 페이지 구조 제작
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  components/EscapeInfo/EscapeInfo.tsx
  components/ListItem/ListItem.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/BookmarkListScreen/BookmarkListScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature

#50 [feat] 전 페이지 공통 스타일 제작
  components/Button/CustomButton.tsx
  components/Button/CustomButtonStyle.tsx
  package.json
  screens/MypageScreen/MypageScreen.tsx
  styles/colors.tsx
  styles/commonStyles.tsx
  yarn.lock
Labels: 🎨 style

#52 [feat] recoil 적용 및 기본 axios 등록
  App.tsx
  components/Button/CustomButton.tsx
  package.json
  recoil/atom/user.tsx
  recoil/selector/selector.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/NonUserFeatureList/NonUserFeatureList.tsx
  screens/MypageScreen/components/UserFeatureList/UserFeatureList.tsx
  yarn.lock
Labels: 💡 feature

#54 [Feat] ReviewScreen layout
  components/CheckBox/CustomCheckBox.tsx
  components/Input/Input.tsx
  package.json
  screens/ReviewScreen/ReviewScreen.tsx
  screens/ReviewScreen/components/BackgroundImg/BackgroundImg.tsx
  screens/ReviewScreen/components/DifficultySlider/DifficultySlider.tsx
  screens/ReviewScreen/components/ReviewBody/ReviewBody.tsx
  screens/ReviewScreen/components/ReviewContent/ReviewContent.tsx
  screens/ReviewScreen/components/ReviewTitle/ReviewTitle.tsx
  screens/ReviewScreen/components/UseHint/UseHint.tsx
  yarn.lock
Labels: 💡 feature

#57 [env] axios api url 등록
  apis/instance.tsx
  constants/urls.tsx
Labels: 🏗 env

#58 [feat] HomeScreen에 지도 띄우기
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/settings.gradle
Labels: 💡 feature

#60 [feat] 지도에 gps 붙이기
  android/app/src/main/AndroidManifest.xml
  components/GeolocationAPI/GeolocationAPI.tsx
  components/Input/Input.tsx
  components/Maps/Map.tsx
  package.json
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  yarn.lock
Labels: 💡 feature, 🛠 refactor

#62 [feat] Button refactoring
  components/Button/Button.tsx
  components/Button/ButtonStyle.tsx
  components/InfoCard/InfoCard.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/LoginScreen/LoginScreen.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/NonUserFeatureList/NonUserFeatureList.tsx
  screens/MypageScreen/components/UserFeatureList/UserFeatureList.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
  screens/ProfileUpdateScreen/ProfileUpdateScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ReviewScreen/ReviewScreen.tsx
  screens/ReviewScreen/components/UseHint/UseHint.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 🛠 refactor

#64 [env] 테스트용 URL 수정 및 로컬 URL 등록
  constants/urls.tsx
  recoil/selector/selector.tsx
Labels: 🏗 env

#66 [Feat] HomeScreen axios test 준비
  components/Fab/Fab.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/SearchScreen/SearchScreen.tsx
Labels: 💡 feature

#67 [feat] axios 테스트를 위한 admin 페이지 추가
  App.tsx
  components/Button/CustomButton.tsx
  components/InfoCard/InfoCard.tsx
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  components/_admin/_AdminRightNavigation/AdminRightNavigation.tsx
  constants/urls.tsx
  recoil/member/member.tsx
  recoil/member/theme.tsx
  recoil/selector/selector.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/LoginScreen/LoginScreen.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/NonUserFeatureList/NonUserFeatureList.tsx
  screens/MypageScreen/components/UserFeatureList/UserFeatureList.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
  screens/ProfileUpdateScreen/ProfileUpdateScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ReviewScreen/ReviewScreen.tsx
  screens/ReviewScreen/components/ReviewContent/ReviewContent.tsx
  screens/ReviewScreen/components/UseHint/UseHint.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature, 🏗 env, 🎨 style

#69 [feat] FAB onPress -> searchStack 연결
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
Labels: 💡 feature

#72 [feat] SearchScreen 페이지에 지도 확대 랜더링 및 검색 데이터로 useState로 밀어넣도록 설계했습니다.
  App.tsx
  components/Maps/Map.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/SearchScreen.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
Labels: 💡 feature

#74 [feat] ThemeDetail에 지도 추가
  App.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature, 🚨 fix

#76 [feat] 테마 및 리뷰 데이터 연결 및 테스트 버튼 수정
  android/app/src/main/res/values/strings.xml
  app.json
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  constants/urls.tsx
  package.json
  recoil/member/member.tsx
  recoil/member/memberFeature.tsx
  recoil/member/theme.tsx
  recoil/review/review.tsx
  recoil/review/reviewFeature.tsx
  recoil/selector/selector.tsx
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
Labels: 📋data

#78 [feat] dummy data를 통한 HomeScreen에 이주의 테마 띄우기 했습니다.
  android/app/build.gradle
  screens/HomeScreen/HomeScreen.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeTest.tsx
  yarn.lock
Labels: 💡 feature

#80 [feat] 배포를 위한 에러 체크, 버전업 및 페이지 디자인 통일
  android/app/build.gradle
  package.json
  recoil/selector/selector.tsx
  screens/BookmarkListScreen/BookmarkListScreen.tsx
  screens/CompareThemeScreen/CompareThemeScreen.tsx
  screens/RankingScreen/RankingScreen.tsx
  screens/RecordScreen/RecordScreen.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
  screens/ReservationWaitingScreen/ReservationWaitingScreen.tsx
Labels: 🚩 distribution, 🎨 style

#82 [style] WeeklyTheme style 변경
  components/EscapeInfo/EscapeInfo.tsx
  constants/urls.tsx
  recoil/theme/theme.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeTest.tsx
  screens/ReviewScreen/ReviewScreen.tsx
  screens/SearchScreen/SearchScreen.tsx
Labels: 🎨 style

#84 [feat] 작지만 필요한 여러 가지 사항
  components/Header/Header.tsx
  constants/urls.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeTest.tsx
Labels: 💡 feature

#89 [feat] Infocard, EscapeInfo 디자인
  components/Button/ButtonStyle.tsx
  components/Button/CustomButton.tsx
  components/EscapeInfo/EscapeInfo.tsx
  components/EscapeInfo/EscapeInfoStyle.tsx
  components/InfoCard/InfoCard.tsx
  components/InfoCard/InfoCardStyle.tsx
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  recoil/theme/themeFeature.tsx
Labels: 🎨 style

#93 [feat] InfoCard 및 theme 데이터 정리
  components/BottomNavigator/BottomNavigator.tsx
  components/InfoCard/InfoCard.tsx
  components/InfoCard/InfoCardStyle.tsx
  recoil/theme/theme.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
  styles/commonStyles.tsx
Labels: 📋 data

#94 [style] 공통 컴포넌트 디자인 (ListItem, Bargraph 디자인)
  components/BarGraph/BarGraph.tsx
  components/BarGraph/BarGraphStyle.tsx
  components/BarGraph/components/BarGraphItem/BarGraphItem.tsx
  components/BarGraph/components/BarGraphItem/BarGraphItemStyle.tsx
  components/ListItem/ListItem.tsx
  components/ListItem/ListItemStyle.tsx
  recoil/selector/selector.tsx
  recoil/theme/theme.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 🎨 style, 📋 data

#96 [feat] HomeScreen의 지도에서 다중 Marker 구현
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
Labels: 💡 feature

#98 [feat] 선택된 마커에 InfoCard 랜더링
  App.tsx
  components/BottomNavigator/BottomNavigator.tsx
  components/InfoCard/InfoCard.tsx
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  yarn.lock
Labels: 💡 feature

#100 [feat] 테마 디테일 페이지 디자인
  android/app/src/main/AndroidManifest.xml
  components/BarGraph/components/BarGraphItem/BarGraphItemStyle.tsx
  components/Button/ButtonStyle.tsx
  components/EscapeInfo/EscapeInfo.tsx
  components/EscapeInfo/EscapeInfoStyle.tsx
  components/_admin/_AdminRightNavigation/AdminRightNavigation.tsx
  package.json
  screens/AlarmScreen/AlarmScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreenStyle.tsx
  screens/ThemeDetailScreen/components/EscapeInfoView/EscapeCharacter.tsx
  screens/ThemeDetailScreen/components/EscapeInfoView/EscapeCharacterStyle.tsx
  screens/ThemeDetailScreen/components/EscapeInfoView/components/EscapeCharacterItem/EscapeCharacterItem.tsx
  screens/ThemeDetailScreen/components/EscapeInfoView/components/EscapeCharacterItem/EscapeCharacterItemStyle.tsx
  screens/ThemeDetailScreen/components/MyReview/MyReview.tsx
  screens/ThemeDetailScreen/components/ThemeStarRate/ThemeStarRate.tsx
  screens/ThemeDetailScreen/components/ThemeStarRate/ThemeStarRateStyle.tsx
  screens/ThemeDetailScreen/components/ThemeTitleContent/ThemeTitleContent.tsx
  screens/ThemeDetailScreen/components/ThemeTitleContent/ThemeTitleContentStyle.tsx
  yarn.lock
Labels: 🚨 fix, 🎨 style, 📡Connect

#102 [feat] dummydata 관리를 위해 useState -> useRecoilState'
  recoil/theme/theme.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
Labels: 💡 feature, 🚨 fix

#104 [feat] InfoCard onPress 연결, stack navigator
  App.tsx
  components/BottomNavigator/BottomNavigator.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
Labels: 💡 feature

#106 [style] 공통컴포넌트(review, fab) 디자인
  components/BarGraph/BarGraphStyle.tsx
  components/BarGraph/components/BarGraphItem/BarGraphItemStyle.tsx
  components/Fab/Fab.tsx
  components/Fab/FabStyle.tsx
  components/Review/ReviewItem.tsx
  components/Review/ReviewStyle.tsx
  recoil/review/review.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/components/MyReview/MyReview.tsx
Labels: 🎨 style

#108 [style] 스크린 페이지 디자인 (HomeScreen)
  components/Input/Input.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/HomeScreen/HomeScreenStyle.tsx
  screens/HomeScreen/components/BookmarkedTheme/BookmarkedTheme.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitle.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitleStyle.tsx
  screens/HomeScreen/components/InputHeadline/InputHeadline.tsx
  screens/HomeScreen/components/InputHeadline/InputHeadlineStyle.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItemStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeStyle.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  styles/commonStyles.tsx
Labels: 🎨 style

#110 [Feat] map region을 recoil에서 관리하기 위한 recoil 작성 및 HomeScreen과 Them
  components/Maps/Map.tsx
  recoil/map/map.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature

#111 [style] 공통 컴포넌트 디자인 (header)
  components/Header/Header.tsx
Labels: 🎨 style

#115 [style] rankingPage 디자인
  components/BottomNavigator/BottomNavigator.tsx
  screens/HomeScreen/HomeScreenStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/RankingScreen/RankingScreen.tsx
  screens/RankingScreen/RankingScreenStyle.tsx
Labels: 🎨 style

#116 [style] 공통컴포넌트 디자인 (캘린더)
  components/Calendar/Calendar.tsx
  components/Calendar/CalendarStyle.tsx
Labels: 🎨 style

#118 [Feat] Modal 생성 및 Screen의 List로 보기 관리
  components/BottomNavigator/BottomNavigator.tsx
  recoil/map/map.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/SearchScreen.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
Labels: 💡 feature

#119 [feat] theme 관련 데이터 연결 및 이미지 출력
  App.tsx
  components/InfoCard/InfoCard.tsx
  components/InfoCard/InfoCardStyle.tsx
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  package.json
  recoil/review/reviewFeature.tsx
  recoil/selector/selector.tsx
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItemStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/RankingScreen/RankingScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreenStyle.tsx
  screens/ThemeDetailScreen/components/ThemeStarRate/ThemeStarRate.tsx
  storage/AsyncService.tsx
  storage/PersonService.tsx
  storage/useCachedResources.tsx
  yarn.lock
Labels: 🎨 style, 📋 data, 📡Connect

#122 [feat] InfoCard 디자인 및 버튼 선택권 제공
  App.tsx
  components/InfoCard/InfoCard.tsx
  components/InfoCard/InfoCardStyle.tsx
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  recoil/theme/theme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
Labels: 🎨 style, 📋 data

#127 [feat] header bar에 navigator 등록
  components/BottomNavigator/BottomNavigator.tsx
  components/Header/Header.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/HomeScreen.tsx
Labels: 💡 feature

#128 [Feat] 바텀바를 사용해 지도 랜더링
  App.tsx
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/HomeScreen.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature, 🚨 fix

#131 [feat] FAB 버튼으로 지도 확대시 내위치 기반 100개 검색
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature

#130 [feat] 카카오 OAuth 로그인
  .gitignore
  android/app/build.gradle
  components/BottomNavigator/BottomNavigator.tsx
  components/InfoCard/InfoCard.tsx
  components/_admin/_AdminAxiosTestBox/AdminAxiosTestBox.tsx
  package.json
  recoil/member/member.tsx
  recoil/member/memberFeature.tsx
  recoil/selector/selector.tsx
  recoil/state/state.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitleStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/LoginScreen/LoginScreen.tsx
  screens/MypageScreen/MypageScreen.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/RankingScreen/RankingScreen.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  styles/commonStyles.tsx
  yarn.lock
Labels: 📋 data, 📡 Connect

#133 [style] 페이지 디자인 (마이페이지, 설정) 및 데이터 연결
  components/BottomNavigator/BottomNavigator.tsx
  components/ListItem/ListItem.tsx
  components/ListItem/ListItemStyle.tsx
  screens/MypageScreen/MypageScreen.tsx
  screens/MypageScreen/MypageScreenStyle.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
  screens/MypageScreen/components/UserProfile/UserProfileStyle.tsx
  screens/SettingScreen/SettingScreen.tsx
  screens/SettingScreen/SettingScreenStyle.tsx
Labels: 🎨 style

#135 [feat] 홈 화면에서 검색 기능
  components/BottomNavigator/BottomNavigator.tsx
  components/Input/Input.tsx
  recoil/search/search.tsx
  screens/HomeScreen/components/InputHeadline/InputHeadline.tsx
  screens/SearchScreen/SearchResultScreen.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchResultMap.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature

#137 [feat] Search 페이지 InfoList 띄우기
  assets/images/image-logo.png
  components/InfoCard/InfoCard.tsx
  components/Input/Input.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/HomeScreenStyle.tsx
  screens/HomeScreen/components/BookmarkedTheme/BookmarkedTheme.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitleStyle.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeStyle.tsx
  screens/RankingScreen/RankingScreenStyle.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreenStyle.tsx
Labels: 🎨 style, 📋 data

#138 [refactor] 리스트로 보기 modal 연결, 그리고 성능 개선
  screens/AlarmScreen/AlarmScreen.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 🚨 fix, 🛠 refactor

#140 [feat] kakao oauth 회원가입 및 로그인 구현
  components/Button/ButtonStyle.tsx
  components/Button/CustomButton.tsx
  recoil/member/memberFeature.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/MypageScreen/MypageScreen.tsx
  screens/MypageScreen/MypageScreenStyle.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  screens/SignUpScreen/SignUpScreenStyle.tsx
Labels: 💡 feature, 🎨 style, 📋 data

#142 [feat] filter 검색 구현/ marker 변경 완료
  screens/HomeScreen/components/InputHeadline/InputHeadline.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchFilter.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMap.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature, 🚨 fix, 🛠 refactor, 📡 Connect

#144 [feat] theme 디테일 페이지 및 데이터 정리
  components/BottomNavigator/BottomNavigator.tsx
  components/Button/CustomButton.tsx
  components/Calendar/Calendar.tsx
  components/EscapeInfo/EscapeInfo.tsx
  components/InfoCard/InfoCard.tsx
  components/Review/ReviewItem.tsx
  components/Review/ReviewStyle.tsx
  recoil/review/review.tsx
  recoil/review/reviewFeature.tsx
  recoil/theme/theme.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreenStyle.tsx
  screens/ThemeDetailScreen/components/MyReview/MyReview.tsx
Labels: 💡 feature, 🎨 style, 📋 data, 📡 Connect

#145 [Save] Reservation Screen 중간저장
  components/Dropdown/Dropdown.tsx
  components/InfoCard/InfoCard.tsx
  components/Input/Input.tsx
  recoil/map/map.tsx
  recoil/selector/selector.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/ReservationScreen/HeadCountSlider/HeadCountSlider.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ReservationScreen/ReservationScreenStyle.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
  screens/SignUpScreen/SignUpScreen.tsx
Labels: 💡 feature

#148 [feat] InfoCard 스프레드로 변경
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
Labels: 💡 feature, 🚨 fix

#152 [feat] 페이지 다자인(search) 및 사용자 편의성 개선
  components/Header/Header.tsx
  recoil/state/state.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItemStyle.tsx
  screens/SearchScreen/SearchScreenBottomTab.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchFilter.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchFilterStyle.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModal.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchListModalStyle.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottomStyle.tsx
Labels: 🎨 style, 📋 data

#154 [feat] 예약 기능 구현
  components/Calendar/Calendar.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/ReservationScreen/ReservationScreen.tsx
Labels: 💡 feature

#156 [feat] 페이지 디자인(예약 내역)
  android/app/build.gradle
  components/BarGraph/BarGraph.tsx
  components/BottomNavigator/BottomNavigator.tsx
  components/EscapeInfo/EscapeInfo.tsx
  components/InfoCard/InfoCard.tsx
  components/Review/ReviewItem.tsx
  package.json
  recoil/member/member.tsx
  recoil/reservation/reservation.tsx
  recoil/reservation/reservationFeature.tsx
  recoil/theme/theme.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/components/BookmarkedTheme/BookmarkedTheme.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/MypageScreen/components/MypageLogin/MypageLogin.tsx
  screens/MypageScreen/components/ReservationInfo/ReservationInfo.tsx
  screens/MypageScreen/components/UserProfile/UserProfile.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ReservationScreen/ReservationScreenStyle.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
Labels: 💡 feature, 🚨 fix, 🎨 style, 📋 data, 📡 Connect

#159 [feat] 회원가입 입력 제한 설정
  package.json
  screens/SignUpScreen/SignUpScreen.tsx
  screens/SignUpScreen/SignUpScreenStyle.tsx
  yarn.lock
Labels: 💡 feature, 🚨 fix, 🎨 style, 📋 data

#161 [feat] starRating 컴포넌트 디자인 및 적용
  components/BottomNavigator/BottomNavigator.tsx
  components/InfoCard/InfoCard.tsx
  components/InfoCard/InfoCardStyle.tsx
  components/MiniInfoCard/MiniInfoCard.tsx
  components/StarRating/StarRating.tsx
  components/StarRating/StarRatingStyle.tsx
  recoil/theme/theme.tsx
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItemStyle.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyTheme.tsx
  screens/HomeScreen/components/WeeklyTheme/WeeklyThemeStyle.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/MypageScreen/components/ReservationInfo/ReservationInfo.tsx
  screens/ThemeDetailScreen/components/ThemeStarRate/ThemeStarRate.tsx
  screens/ThemeDetailScreen/components/ThemeStarRate/ThemeStarRateStyle.tsx
Labels: 💡 feature, 🎨 style, 📋 data

#163 [fix] 지도 컴포넌트 수정
  assets/icons/icon-marker-main3.png
  assets/icons/icon-marker-main5.png
  assets/icons/icon-marker-red.png
  components/Maps/Map.tsx
  components/Maps/MyLocationMarker/MyLocationMarker.tsx
  recoil/map/map.tsx
  screens/HomeScreen/components/InputHeadline/InputHeadline.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchFilter.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature, 🚨 fix

#167 [feat] 리뷰 정보 디자인 수정
  components/BottomNavigator/BottomNavigator.tsx
  components/InfoCard/InfoCard.tsx
  components/MiniInfoCard/MiniInfoCard.tsx
  components/Review/ReviewItem.tsx
  components/Review/ReviewStyle.tsx
  components/StarRating/StarRating.tsx
  components/StarRating/StarRatingStyle.tsx
  screens/AlarmScreen/AlarmScreen.tsx
  screens/HomeScreen/components/RenderThemeItem/RenderThemeItem.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature, 🎨 style, 📋 data

#170 [feat] 상세페이지 디자인 (지도 높이 높이기), 테마 상세 들어갈 때 로딩
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreenStyle.tsx
Labels: 🎨 style

#171 [feat] FCM 알림 기능 추가
  App.tsx
  assets/icons/icon-marker.png
  package.json
  recoil/theme/themeFeature.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
  yarn.lock
Labels: 💡 feature

#173 [fix] 지도 배율 수정
  recoil/map/map.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 🚨 fix, 🎨 style

#175 [feat] kakao 로그인 시 백으로 fcm 토큰 전달
  App.tsx
  package.json
  recoil/map/map.tsx
  screens/HomeScreen/components/HomeTitle/HomeTitle.tsx
  screens/HomeScreen/components/NearByTheme/NearByTheme.tsx
  screens/KakaoLoginScreen/KakaoLoginScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
  yarn.lock
Labels: 💡 feature, 🚨 fix, 🛠 refactor

#177 [feat] toast 알림 구현
  App.tsx
  screens/SearchScreen/components/SearchScreenMap/SearchScreenMapBottom.tsx
Labels: 💡 feature, 🚨 fix

#180 [style] Readme 수정
  README.md
  package.json
  yarn.lock
Labels: 🎨 style
