Repository rainbowgon/opentheDoor-frontend, pull requests merged in 2023-10, with the labels that each got.

#2 [env] FrontEnd 프로젝트 생성
  .bundle/config
  .eslintrc.js
  .gitignore
  .prettierrc.js
  .watchmanconfig
  App.tsx
  Gemfile
  README.md
  __tests__/App.test.tsx
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/com/openthedoor/ReactNativeFlipper.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/openthedoor/MainActivity.java
  android/app/src/main/java/com/openthedoor/MainApplication.java
  android/app/src/main/res/drawable/rn_edit_text_material.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/release/java/com/openthedoor/ReactNativeFlipper.java
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  app.json
  babel.config.js
  index.js
  ios/.xcode.env
  ios/OpenTheDoor.xcodeproj/project.pbxproj
  ios/OpenTheDoor.xcodeproj/xcshareddata/xcschemes/OpenTheDoor.xcscheme
  ios/OpenTheDoor/AppDelegate.h
  ios/OpenTheDoor/AppDelegate.mm
  ios/OpenTheDoor/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/OpenTheDoor/Images.xcassets/Contents.json
  ios/OpenTheDoor/Info.plist
  ios/OpenTheDoor/LaunchScreen.storyboard
  ios/OpenTheDoor/main.m
  ios/OpenTheDoorTests/Info.plist
  ios/OpenTheDoorTests/OpenTheDoorTests.m
  ios/Podfile
  jest.config.js
  metro.config.js
  package.json
  tsconfig.json
  yarn.lock
Labels: 🏗 env

#4 [env] FrontEnd 프로젝트 수정
  .gitignore
  android/app/debug.keystore
  android/app/src/main/java/com/openthedoor/MainActivity.java
  android/app/src/main/res/values/strings.xml
  android/gradle/wrapper/gradle-wrapper.jar
  android/settings.gradle
  app.json
  ios/OpenTheDoor.xcodeproj/project.pbxproj
  ios/OpenTheDoor.xcodeproj/xcshareddata/xcschemes/OpenTheDoor.xcscheme
  ios/OpenTheDoor/AppDelegate.mm
  ios/OpenTheDoor/Info.plist
  ios/OpenTheDoor/LaunchScreen.storyboard
  ios/OpenTheDoorTests/OpenTheDoorTests.m
  ios/Podfile
  package.json
  yarn.lock
Labels: 🚨 fix, 🏗 env

#7 bottomTab 적용
  .eslintrc.js
  .prettierrc.js
  App.tsx
  package.json
  screens/HomeScreen/HomeScreen.tsx
  screens/MypageScreen/MypageScreen.tsx
  screens/SearchScreen/SearchScreen.tsx
  yarn.lock
Labels: 💡 feature

#11 [feat] button, listItem, InfoCard 공통 컴포넌트 틀 제작
  .prettierrc.js
  components/button/Button.tsx
  components/button/CustomButton.tsx
  components/infoCard/InfoCard.tsx
  components/listItem/ListItem.tsx
  package.json
  yarn.lock
Labels: 💡 feature

#13 Feat/9
  babel.config.js
  components/dropdown/Dropdown.tsx
  components/fab/Fab.tsx
  components/header/Header.tsx
  components/input/Input.tsx
  index.js
  package.json
  screens/HomeScreen/HomeScreen.tsx
  yarn.lock
Labels: 💡 feature

#16 [fix] 변경 요청 사항 수정 (dropbox의 props 제외)
  components/button/CustomButton.tsx
  components/fab/Fab.tsx
  components/infoCard/InfoCard.tsx
  components/listItem/ListItem.tsx
  screens/HomeScreen/HomeScreen.tsx
Labels: 🚨 fix

#21 [fix] component 폴더 convention에 맞춰 변경
  components/Dropdown/Dropdown.tsx
  components/Fab/Fab.tsx
  components/Header/Header.tsx
  components/Input/Input.tsx
  screens/HomeScreen/HomeScreen.tsx
Labels: 🚨 fix

#23 [feat] 전체 Page 제작 및 Page 접근을 위한 개발용 nav 생성
  App.tsx
  babel.config.js
  components/BarGraph/BarGraph.tsx
  components/BarGraph/components/BarGraphItem/BarGraphItem.tsx
  components/_AdminFabGroup/AdminRightNavigation.tsx
  package.json
  screens/AlarmScreen/AlarmScreen.tsx
  screens/BookmarkListScreen/BookmarkListScreen.tsx
  screens/CompareThemeScreen/CompareThemeScreen.tsx
  screens/LoginScreen/LoginScreen.tsx
  screens/ProfileUpdateScreen/ProfileUpdateScreen.tsx
  screens/RankingScreen/RankingScreen.tsx
  screens/RecordScreen/RecordScreen.tsx
  screens/ReservationListScreen/ReservationListScreen.tsx
  screens/ReservationScreen/ReservationScreen.tsx
  screens/ReservationWaitingScreen/ReservationWaitingScreen.tsx
  screens/ReviewScreen/ReviewScreen.tsx
  screens/SettingScreen/SettingScreen.tsx
  screens/SignUpScreen/SignUpScreen.tsx
  screens/ThemeDetailScreen/ThemeDetailScreen.tsx
  yarn.lock
Labels: 💡 feature

#25 [feat] FCM 기능 구현
  .prettierrc.js
  App.tsx
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/java/com/openthedoor/MainActivity.java
  android/app/src/main/java/com/openthedoor/MyFirebaseMessagingService.java
  android/build.gradle
  ios/opentheDoor.xcodeproj/project.pbxproj
  ios/opentheDoor.xcodeproj/xcshareddata/xcschemes/OpenTheDoor.xcscheme
  ios/opentheDoor/AppDelegate.h
  ios/opentheDoor/AppDelegate.mm
  ios/opentheDoor/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/opentheDoor/Images.xcassets/Contents.json
  ios/opentheDoor/Info.plist
  ios/opentheDoor/LaunchScreen.storyboard
  ios/opentheDoor/main.m
  ios/opentheDoorTests/Info.plist
  ios/opentheDoorTests/OpenTheDoorTests.m
  package.json
  screens/HomeScreen/HomeScreen.tsx
  screens/MypageScreen/MypageScreen.tsx
  yarn.lock
Labels: 💡 feature
